CREATE DATABASE IF NOT EXISTS VOTING_APP;

USE VOTING_APP;

CREATE TABLE IF NOT EXISTS DEPARTMENT (
    NAME VARCHAR(30) NOT NULL PRIMARY KEY
);

INSERT IGNORE INTO DEPARTMENT (NAME)
VALUES ('COMPUTER SCIENCE'),
       ('MATHEMATICS'),
       ('PHYSICS'),
       ('ADMIN'),
       ('CHEMISTRY');

CREATE TABLE IF NOT EXISTS `POSITION` (
    TITLE VARCHAR(30) NOT NULL PRIMARY KEY
);

INSERT IGNORE INTO `POSITION` (TITLE) VALUES
       ('PRESIDENT'),
       ('VICE PRESIDENT'),
       ('SECRETARY');

CREATE TABLE IF NOT EXISTS USERS (
    USERNAME VARCHAR(10) NOT NULL PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEPARTMENT_NAME VARCHAR(30),
    PASSWORD VARCHAR(50) NOT NULL,
    FOREIGN KEY (DEPARTMENT_NAME) REFERENCES DEPARTMENT(NAME) ON DELETE RESTRICT
);

INSERT IGNORE INTO USERS (USERNAME, FNAME, LNAME, PASSWORD, DEPARTMENT_NAME) VALUES
       ('ADMIN', 'ADMIN', 'ADMIN', 'Admin123', NULL);

CREATE TABLE IF NOT EXISTS ADMIN (
    USERNAME VARCHAR(10) NOT NULL UNIQUE,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE RESTRICT
);

INSERT IGNORE INTO ADMIN (USERNAME) VALUES ('ADMIN');

CREATE TABLE IF NOT EXISTS CANDIDATES (
    USERNAME VARCHAR(10) NOT NULL,
    POSITION_TITLE VARCHAR(30) NOT NULL,
    `YEAR` INT NOT NULL,
   `DISQUALIFIED` BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE RESTRICT,
    FOREIGN KEY (POSITION_TITLE) REFERENCES `POSITION`(TITLE) ON DELETE RESTRICT,
    PRIMARY KEY (USERNAME, `YEAR`)
);

CREATE TABLE IF NOT EXISTS VOTES (
    VOTER_ID VARCHAR(10) NOT NULL,
    CANDIDATE_ID VARCHAR(10) NOT NULL,
    VOTE_YEAR INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VOTER_ID) REFERENCES USERS(USERNAME) ON DELETE RESTRICT,
    FOREIGN KEY (CANDIDATE_ID) REFERENCES USERS(USERNAME) ON DELETE RESTRICT,
    PRIMARY KEY (VOTER_ID, CANDIDATE_ID, VOTE_YEAR)
);